<a href="https://colab.research.google.com/github/Jeoneunjae/prac_class/blob/main/2021_04_01_python_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Phython Practice

Chapter 2: Numeric operations


*   four fundamental arithmatic operations(+, -, /, *)
*   power(**)
*   quotient몫 and remainder나머지(%,//)

In [ ]:
1+3

4

In [ ]:
5-2

3

In [ ]:
4/2

2.0

In [ ]:
5*3

15

In [ ]:
5**2

25

In [ ]:
3%2

1

In [ ]:
3//2

1

string operations

*   how to define string("-", '0', ""0"", and"'0'")
*   escape codes
*   string operations(+, *)
*   indexing
*   formating
*   string functions(join, split, upper, lower, strip, ...)







In [ ]:
str1 = "this is a string"

In [ ]:
str1 = """a man talked "hi jain". 'dfdf' in \n \t fdfd  """

In [ ]:
print(str1)

a man talked "hi jain". 'dfdf' in 
 	 fdfd  


In [ ]:
str = "aab" 
strB = "ccd"

In [ ]:
str+strB

'aabccd'

In [ ]:
str*3

'aabaabaab'

In [ ]:
str = "aabccd" 

In [ ]:
str[1:-3]

'ab'

In [ ]:
a = "40"

"varible A: {}".format(a)

'varible A: 40'

In [ ]:
print( "varible A: {}".format(a) )

varible A: 40


In [ ]:
alist = ["a","b","c"]
alist

['a', 'b', 'c']

In [ ]:
b = " ".join(alist)
b

'a b c'

In [ ]:
b.split()

['a', 'b', 'c']

In [ ]:
b.upper()

'A B C'

list

*   how to define a list
*   indexing
*   list operations(+, *, len)
*   some functions with list(appnd, sort, reverse,...)

In [ ]:
a = [1,2,3,4,0,-1]
a

[1, 2, 3, 4, 0, -1]

In [ ]:
b = [1,2, "ab", 4]
b

[1, 2, 'ab', 4]

In [ ]:
c = [1,2,[1,2], [1,2,[1,2,3]]]
c

[1, 2, [1, 2], [1, 2, [1, 2, 3]]]

In [ ]:
c[2][1] #c의 3번째의 2번째 항목

2

In [ ]:
c[3][2][0]

1

In [ ]:
len(c) #length of c

4

In [ ]:
a.sort() #크기 순서대로 나열
a

[-1, 0, 1, 2, 3, 4]

In [ ]:
a.append(10) #10추가
a

[-1, 0, 1, 2, 3, 4, 10]

In [ ]:
a.reverse() #순서 뒤집기
a

[10, 4, 3, 2, 1, 0, -1]

Dictionary

*   how to define a dictionary
*   functions(keys, values, items, get, in)

In [ ]:
dic = {'name':'pey', 'phone':'0119993323', 'birth': '1118'}
dic

{'birth': '1118', 'name': 'pey', 'phone': '0119993323'}

In [ ]:
dic['birth']

'1118'

In [ ]:
dic['newkey1']=123
dic

{'birth': '1118', 'name': 'pey', 'newkey1': 123, 'phone': '0119993323'}

In [ ]:
dic. keys()

dict_keys(['name', 'phone', 'birth', 'newkey1'])

In [ ]:
dic. values()

dict_values(['pey', '0119993323', '1118', 123])

In [ ]:
dic. items()

dict_items([('name', 'pey'), ('phone', '0119993323'), ('birth', '1118'), ('newkey1', 123)])

In [ ]:
for (key,value) in dic.items() : 
  print("key:{}, value:{}".format(key,value)) #for loops

key:name, value:pey
key:phone, value:0119993323
key:birth, value:1118
key:newkey1, value:123


In [ ]:
dic. get('phone')

'0119993323'

In [ ]:
'name' in ['name', 'aaa'] #['name', 'aaa'] 안에 'name' 있으므로 true

True

chapter 2 practice

1) remove duplicates

In [ ]:
a = [1, 1, 1, 2, 2, 3, 3, 3, 4, 4, 5]

In [ ]:
a = [1, 1, 1, 2, 2, 3, 3, 3, 4, 4, 5]
list(set(a))

[1, 2, 3, 4, 5]

2) how to extract 'A' and 'B' from the list 'a'?

In [ ]:
a = {'A':90, 'B':80, 'C':70}

In [ ]:
a['A']

90

3) what is the result?

In [ ]:
a = b = [1, 2, 3]
a[1] = 4
print(b)

[1, 4, 3]


chapter 3

if else

In [ ]:
if 1 :
  print("Do it")
else :
  print("cond not true")

Do it


In [ ]:
if 0 :
  print("Do it")
else :
  print("cond not true")

cond not true


In [ ]:
a = 10; b = 0

In [ ]:
if a > 0 :
  print("Do it")
else :
  print("cond not true")

Do it


In [ ]:
name = 'Tom'; listofnames = ['Tom', 'Jane', 'Karl']

In [ ]:
if name not in listofnames :
  print("Do it")
else :
  print("cond not true")

cond not true


for loop

In [ ]:
for i in range(5) :
  print(i)

0
1
2
3
4


In [ ]:
for name in listofnames :
  print(name)

Tom
Jane
Karl


In [ ]:
dic

{'birth': '1118', 'name': 'pey', 'newkey1': 123, 'phone': '0119993323'}

In [ ]:
for (key,value) in dic.items() :
  print(key, value)

name pey
phone 0119993323
birth 1118
newkey1 123


chapter 4

function

In [ ]:
afunc <- function(a,b) {
    xdfdsfdsfd

    return (a+b)
}
#in R

In [ ]:
if 0 :
  print("hi")
  print("bye")
print("2")
#in R, tab is very important

2


In [ ]:
def add(a, b):
  return a+b

In [ ]:
print(add(3, 4))  

7


file read and write

In [ ]:
with open('ids.txt', 'w') as f :
    f.write('ID\nJohn\nKarl\nAndy\nTim\n')

In [ ]:
with open('data1.txt', 'w') as f :
    f.write('ID\tfield1\tfield2\tfield3\nTom\t1\t3\t1\nJohn\t1\t3\t3\nTom\t1\t1\t1\nKarl\t1\t1\t2\nKarl\t1\t3\t2\nKarl\t2\t2\t2\nAndy\t1\t2\t3')

In [ ]:
with open('data2.txt', 'w') as f :
    f.write('ID\tfield1\tfield2\tfield3\nTom\t2\t3\t1\nJane\t1\t1\t3\nJane\t2\t2\t1\nMax\t3\t1\t2\nKarl\t1\t4\t2\nMax\t3\t2\t2\nMax\t2\t2\t1\nTom\t2\t3\t1\nJane\t1\t1\t3\nJane\t2\t2\t1\nMax\t3\t1\t2\nKarl\t1\t4\t2\nMax\t3\t2\t2\nMax\t2\t2\t1')

read data

In [ ]:
ids = []
with open('ids.txt', 'r') as f :
    for line in f :
#        print(line)
        ids.append(line.strip())

In [ ]:
ids

['ID', 'John', 'Karl', 'Andy', 'Tim']

In [ ]:
%%time

ids = []
V1s = []
with open('data1.txt', 'r', encoding='utf-8') as f :
    for item in f :
        print(item)
        ID, field1, _, _ = item.strip().split()
        ids.append(ID)
        V1s.append(field1)

ID	field1	field2	field3

Tom	1	3	1

John	1	3	3

Tom	1	1	1

Karl	1	1	2

Karl	1	3	2

Karl	2	2	2

Andy	1	2	3
CPU times: user 2.68 ms, sys: 0 ns, total: 2.68 ms
Wall time: 4.74 ms


data genterator

generator from data file

In [ ]:
import sys

In [ ]:
fnm = 'data2.txt'

In [ ]:
def fgenerator(fnm, iter_option = 0) :
    with open(fnm, 'r', encoding='utf-8') as f :
        for idx, item in enumerate(f) :
            ID, V1, V2, V3 = item.strip().split()
            if iter_option == 0 :
                yield ID
            elif iter_option == 1 :
                yield V1
            elif iter_option == 2 :
                yield V2
            else :
                yield V3

In [ ]:
gen_from_file = fgenerator(fnm)

In [ ]:
next(gen_from_file)

'ID'

In [ ]:
for i in gen_from_file :
  print(i)

Tom
Jane
Jane
Max
Karl
Max
Max
Tom
Jane
Jane
Max
Karl
Max
Max


In [ ]:
sys.getsizeof(gen_from_file)

128

In [ ]:
def freader(fnm, iter_option = 0) :
    IDs = []
    with open(fnm, 'r', encoding='utf-8') as f :
        for idx, item in enumerate(f) :
            ID, V1, V2, V3 = item.strip().split()
            if iter_option == 0 :
                IDs.append(ID)
            elif iter_option == 1 :
                IDs.append(V1)
            elif iter_option == 2 :
                IDs.append(V2)
            else :
                IDs.append(V3)
    return IDs

In [ ]:
%%time
res = freader(fnm, 0)

CPU times: user 172 µs, sys: 0 ns, total: 172 µs
Wall time: 178 µs


In [ ]:
res

['ID',
 'Tom',
 'Jane',
 'Jane',
 'Max',
 'Karl',
 'Max',
 'Max',
 'Tom',
 'Jane',
 'Jane',
 'Max',
 'Karl',
 'Max',
 'Max']

In [ ]:
sys.getsizeof(res)

200

generator with class

In [ ]:
class DataGenerator() : 
    def __init__(self, fnm, iter_option=0) :
        self.fnm = fnm
        self.iter_option = iter_option
    
    def __iter__(self) :
        with open(fnm, 'r', encoding='utf-8') as f :
            for idx, item in enumerate(f) :
                ID, V1, V2, V3 = item.strip().split()
                if self.iter_option == 0 :
                    yield ID
                elif self.iter_option == 1 :
                    yield V1
                elif self.iter_option == 2 :
                    yield V2
                else :
                    yield V3
    
    def __len__(self) :
        with open(fnm, 'r', encoding='utf-8') as f :
            for idx, item in enumerate(f) :
                pass
            
            return idx

In [ ]:
fnm = 'data2.txt'

In [ ]:
gen1 = DataGenerator(fnm)

In [ ]:
len(gen1)

14

In [ ]:
for idx, item in enumerate(gen1) :
    print(item)

ID
Tom
Jane
Jane
Max
Karl
Max
Max
Tom
Jane
Jane
Max
Karl
Max
Max


numpy library

*   NumPy stands for 'Numerical Python' or 'Numeric Python'.
*   provides fast mathematical computation on arrays an matrices.



In [ ]:
import numpy as np

In [ ]:
import numpy

np.array()

In [ ]:
a = np.array([1,2,3,4,5,0]) # usually use np instead of numpy for the short-term.
b = [1,2,3,4,5]

differences?

In [ ]:
b+b

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
a+a

array([ 2,  4,  6,  8, 10,  0])

In [ ]:
a*a

array([ 1,  4,  9, 16, 25,  0])

In [ ]:
a@a

55

In [ ]:
a.shape

(6,)

generating numpy arrays

*   np.ones()
*   np.zeros()
*   np.arrange()
*   np.full()





In [ ]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.full([2,3], -1) #2*3 matrix
a

array([[-1, -1, -1],
       [-1, -1, -1]])

In [ ]:
a.T #transpose

array([[-1, -1],
       [-1, -1],
       [-1, -1]])

numpy array indexing

In [ ]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[:-3] #맨 뒤 3개 빼고 앞에꺼 전부 나열

array([1, 2, 3, 4, 5, 6])

In [ ]:
a[-3:] #맨 뒤 3개 나열

array([7, 8, 9])

In [ ]:
a[2:5]

array([3, 4, 5])

In [ ]:
a[0:10:2]

array([1, 3, 5, 7, 9])

In [ ]:
b = np.arange(0,10).reshape(2,5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
b[:,2:]

array([[2, 3, 4],
       [7, 8, 9]])

useful np functions

*   np.abs()
*   np.exp()
*   np.pow()
*   np.log()
*   np.sqrt()

In [ ]:
a = np.arange(-3,5)
a

array([-3, -2, -1,  0,  1,  2,  3,  4])

In [ ]:
np.abs(a)

array([3, 2, 1, 0, 1, 2, 3, 4])

In [ ]:
np.exp(a)

array([4.97870684e-02, 1.35335283e-01, 3.67879441e-01, 1.00000000e+00,
       2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01])

In [ ]:
np.power(a,2)

array([ 9,  4,  1,  0,  1,  4,  9, 16])

In [ ]:
np.log( np.array([2,4,8]))

array([0.69314718, 1.38629436, 2.07944154])

In [ ]:
np.log2( np.array([2,4,8]))

array([1., 2., 3.])

statistics

In [ ]:
a

array([-3, -2, -1,  0,  1,  2,  3,  4])

In [ ]:
np.mean(a)

0.5

In [ ]:
np.median(a)

0.5

In [ ]:
np.std(a)

2.29128784747792